# 日志配置文件
version: 1
disable_existing_loggers: false

# 格式化器
formatters:
  standard:
    format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  detailed:
    format: '%(asctime)s [%(levelname)s] %(name)s [%(filename)s:%(lineno)d]: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  simple:
    format: '[%(levelname)s] %(message)s'

# 处理器
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  
  file_info:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: logs/daily/app.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf-8
  
  file_error:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/error/error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf-8
  
  file_debug:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/debug/debug.log
    maxBytes: 10485760  # 10MB
    backupCount: 3
    encoding: utf-8

# 日志器
loggers:
  # 下载器日志
  downloader:
    level: INFO
    handlers: [console, file_info, file_error]
    propagate: false
  
  # 清洗器日志
  cleaner:
    level: INFO
    handlers: [console, file_info, file_error]
    propagate: false
  
  # 分析器日志
  analyzer:
    level: INFO
    handlers: [console, file_info, file_error]
    propagate: false
  
  # 分类器日志
  classifier:
    level: INFO
    handlers: [console, file_info, file_error]
    propagate: false
  
  # 解析器日志
  parser:
    level: INFO
    handlers: [console, file_info, file_error]
    propagate: false
  
  # AI客户端日志
  ai_client:
    level: INFO
    handlers: [console, file_info, file_error]
    propagate: false
  
  # 文件管理器日志
  file_manager:
    level: INFO
    handlers: [console, file_info, file_error]
    propagate: false
  
  # 配置管理器日志
  config_manager:
    level: INFO
    handlers: [console, file_info, file_error]
    propagate: false

# 根日志器
root:
  level: INFO
  handlers: [console, file_info, file_error]

# 第三方库日志级别
loggers:
  requests:
    level: WARNING
    propagate: true
  
  urllib3:
    level: WARNING
    propagate: true
  
  zhipuai:
    level: INFO
    propagate: true
  
  openai:
    level: INFO
    propagate: true
